# Generated by Django 3.0.6 on 2020-05-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200518_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
